# Logging configuration are defined here

version: 1
disable_existing_loggers: False


formatters:
  plain:
    format: "%(asctime)s - %(levelname)s: %(message)s"

  simple:
    format: "%(asctime)s - %(levelname)-8s - %(name)-12s: %(message)s"

  colored:
    (): "colorlog.ColoredFormatter"
    format: "%(log_color)s%(levelname)-8s%(reset)s %(blue)s%(message)s"


handlers:
  console:
    class: "logging.StreamHandler"
    formatter: colored
    level: INFO
    stream: "ext://sys.stdout"

  debug_file_handler:
    class: "logging.handlers.RotatingFileHandler"
    formatter: plain
    filename: "debug.log"
    level: DEBUG
    maxBytes: 10485760  # 10 MB
    backupCount: 20
    encoding: "utf8"

  info_file_handler:
    class: "logging.handlers.RotatingFileHandler"
    formatter: plain
    filename: "info.log"
    level: INFO
    maxBytes: 10485760  # 10 MB
    backupCount: 20
    encoding: "utf8"


loggers:
  qtgui:
    level: INFO
    handlers: [debug_file_handler, info_file_handler]
    propagate: no


root:
  level: INFO
  handlers: [console]
